### ISSUE TITLE
Consider using Algolia for search

### ISSUE THREAD

**Issue by Haroenv** [GAntoine/search-flow-typed#3]
Hey, I work for Algolia and saw this project. It would be nice for features like typo-tolerance to simply add a script to push to Algolia and use for example React InstantSearch to display and filter the results. 

This will most probably fit under our free plan, and if it wouldn't, then it'd fit under the open source plan. 

Happy to help setting it up!

**Comment by gantoine** [comment]
Hey, thanks for reaching out! I'm absolutely interested in using Algolia, I've seen some of what it offers. What would the setup process entail?

**Comment by Haroenv** [comment]
on a build step, you would get all flow definitions, push them to Algolia (maybe deduplicate first by getting the data from Algolia before pushing). Then you can decide some settings (maybe track them in a file here too and apply them on build), and you can make an interface with the api client, or with a library like [react-instantsearch](https://community.algolia.com/react-instantsearch)

Does that make sense,

**Comment by gantoine** [comment]
Yeah that makes sense, I'll probably do it through `react-instantsearch`. I've got some time at the end of the week, so I'll probably add it around then.
Since definitions change many times a day, how often am I able to push those changes to Algolia? Like anytime a definition changes VS once a day VS when I deploy this project.

**Comment by Haroenv** [comment]
It would be best to have some watcher for the definitions, update them when needed. that way you don't need to do a complete batch.

**Comment by gantoine** [comment]
Alright, I've got a PR open and a test app at [flow-algolia.surge.sh](http://flow-algolia.surge.sh). Everything looks nice and snappy. 👌  I won't publish this until I figure out the best way to update the index, but after the work done here I'm hopeful. Thanks again for the suggestion and the guidance!

**Comment by Haroenv** [comment]
looks lovely! Since you already had a process in place to keep things in sync with the definitions, it should be straightforward

**Comment by Haroenv** [comment]
Some feedback from @seafoox: you can use the `<Highlight />` component in the hits for having more knowledge why a certain item is picked 💡

**Comment by gantoine** [comment]
> Since you already had a process in place to keep things in sync with the definitions, it should be straightforward

Yeah, about that... My method was fetching all the definitions and parsing them client-side when a user loads the app. 😅  I'll need to talk with the flow team about setting up a webhook to update on deploy, but I don't expect that to be too difficult.

**Comment by Haroenv** [comment]
A GitHub web hook should do the trick
